SELECT AGE,LENGTH(AGE), studentid,LENGTH(studentid) FROM studenttable
SELECT STARTDATE,LENGTH(STARTDATE) FROM coursetable
SELECT STARTDATE,TO_CHAR(STARTDATE) FROM coursetable
SELECT AGE,TO_CHAR(AGE) FROM studenttable
SELECT AGE,TO_CHAR(AGE,'$99.99') FROM studenttable
SELECT to_char(sysdate, 'dd-mon-yyyy hh24:mi:ss') FROM coursetable
SELECT SYSDATE FROM coursetable
SELECT STARTDATE,to_char(STARTDATE, 'YYYYMMDD') FROM coursetable
SELECT STUDENTNAME,TO_NUMBER(STUDENTNAME) FROM studenttable
SELECT COURSEPERIOD,COURSESCORE,TO_NUMBER(COURSEPERIOD）* coursescore FROM COURSETABLE
SELECT STARTDATE,TO_NUMBER(STARTDATE) FROM coursetable
SELECT trunc(SYSDATE, 'YEAR') FROM coursetable
SELECT to_date(STARTDATE, 'YYYY-MM-DD HH24:Mi:SS') FROM coursetable
SELECT TO_DATE('2005-01-01 13:14:20','YYYY-MM-DD hh24:mi:ss') FROM coursetable
SELECT SYSDATE,TO_CHAR(SYSDATE,'DDD') 年第几天,TO_CHAR(SYSDATE,'WW') 年第几周,TO_CHAR(SYSDATE,'W') 月第几周,TO_CHAR(SYSDATE,'D') 星期几 FROM scoretable
SELECT SYSDATE,TO_CHAR(SYSDATE,'DAY'),TO_CHAR(SYSDATE,'D') FROM coursetable
SELECT SYSDATE,TO_CHAR(SYSDATE,'YYYY'),TO_CHAR(SYSDATE,'Q'),TO_CHAR(SYSDATE,'MM'),TO_CHAR(SYSDATE,'DD'),TO_CHAR(SYSDATE,'DAY'),TO_CHAR(SYSDATE,'HH'),TO_CHAR(SYSDATE,'HH24'),TO_CHAR(SYSDATE,'MI'),TO_CHAR(SYSDATE,'SS') FROM coursetable
SELECT GREATEST(STUDENTNAME) FROM STUDENTTABLE
SELECT DISTINCT GREATEST('AB','aE','BC'),LEAST('AB','aE','BC'),GREATEST(coursename,COURSETEACHER) FROM coursetable
SELECT LEAST(STARTDATE,ENDDATE) FROM coursetable
SELECT USER FROM coursetable
SELECT SYSDATE FROM coursetable
SELECT MAX(AGE) FROM studenttable
SELECT SUM(STUDENTNAME) FROM studenttable
SELECT STATE AS "WHERE'S Queena" FROM studenttable WHERE studentname = 'Queena'
SELECT * FROM STUDENTTABLE WHERE studentname LIKE('Qu%')
SELECT * FROM STUDENTTABLE WHERE STUDENTNAME STARTING WITH ('Qu')
SELECT * FROM studenttable WHERE studentname STARTING WITH('Qu')
SELECT * FROM studenttable ORDER BY AGE
SELECT * FROM studenttable ORDER BY AGE DESC
SELECT * FROM studenttable ORDER BY studentid, studentname DESC;
SELECT * FROM studenttable ORDER BY 2, studentid DESC;
SELECT studentname,SUM(score) FROM scoretable GROUP BY studentname;