SELECT A,B, ceil(B), power(A, CEIL(B)) FROM numbers
SELECT A,SIGN(A) FROM numbers
SELECT * FROM numbers WHERE SIGN(A) = -1
SELECT A,B,LOG(A,B) FROM numbers WHERE SIGN(A) = 1
SELECT A,SQRT(A) FROM numbers
SELECT A,SQRT(abs(A)) FROM numbers
SELECT A,SQRT(A) FROM NUMBERS WHERE SIGN(A) != -1
SELECT AGE, chr(age) FROM studenttable
SELECT STUDENTNAME,FIRSTNAME, concat(STUDENTNAME, FIRSTNAME) "THIS THAT" FROM studenttable